mkdir "Moln†r G†bor"
mkdir "Alm†si Bence"
mkdir "BorbÇly Viktor"
mkdir "D¢sa Andr†s"
mkdir "Dud†s Bence"
mkdir "Csillag Csaba"
mkdir "Deme Tam†s Andr†s"
mkdir "Cseke Rich†rd"
mkdir "Falusi Bence PÇter"
mkdir "Fazekas Levente Bal†zs"
mkdir "FehÇr D†niel"
mkdir "Gyîngyîsi D†vid"
mkdir "Kalina Tam†s Zolt†n"
mkdir "Kalugyer Zsombor"
mkdir "Juh†sz PÇter"
mkdir "Kop†nyi Gergely"
mkdir "Macsinga GÇza"
mkdir "MÅller Zsanett Petra"
mkdir "Kocsis Bars Nimr¢d"
mkdir "Piovarcs Patrik"
mkdir "Szab¢ Hunor Attila"
mkdir "Schweitzer µd†m D†vid"
mkdir "Sendula M†rk"
mkdir "P†rdi Anna µgnes"
mkdir "Szendefy L†szl¢ Erik"
mkdir "Szl†vik Rich†rd Rajmund"
mkdir "Ol†h G†bor"
mkdir "S†ray Anna"
mkdir "Szonda Norbert"
mkdir "Piller G†sp†r Bence"
mkdir "Nagy Dorina Laura"
mkdir "Tak†cs Roland"
mkdir "Tyitova Irina"
mkdir "Verba Mil†n"
mkdir "Zsichla Gergã"
mkdir "Geszler M†tÇ"
mkdir "Gallai J¢zsef"
