mkdir "Patai Szabolcs Lajos"
mkdir "Szilágyi Zsolt"
mkdir "Demeter István Tamás"
mkdir "Máté Patrik"
mkdir "Sándor Norbert"
mkdir "Szivós Patrik Dávid"
mkdir "Szabó Marcell"
mkdir "Hollik Evelin"
mkdir "Tasnádi Richárd"
mkdir "Szegedi Péter"
mkdir "Losonczi József Krisztián"
mkdir "Gajdán Edit Ilona"
mkdir "Dankó Anett"
mkdir "Maták Etele Zétény"
mkdir "Ozsvárt Bence"
